name: PlayerAuctions
version: 3.0.0
main: com.minekarta.playerauction.PlayerAuction
author: MinekartaStudio
api-version: '1.21'
depend: [Vault]
softdepend: [PlaceholderAPI, KartaEmeraldCurrency]



permissions:
  playerauctions.use:
    description: Allows opening the main auction house GUI and using basic features.
    default: true
  playerauctions.sell:
    description: Allows listing items for sale using /ah sell.
    default: true
  playerauctions.cancel:
    description: Allows cancelling your own auctions.
    default: true
  playerauctions.reload:
    description: Allows reloading the plugin's configuration files.
    default: op
  playerauctions.admin:
    description: Access to all administrative features.
    default: op
    children:
      playerauctions.reload: true
      playerauctions.categories: true
      playerauctions.notify: true
      playerauctions.history: true
      playerauctions.history.others: true

  playerauctions.categories:
    description: Allows using /ah categories.
    default: true
  playerauctions.notify:
    description: Allows toggling notifications.
    default: true
  playerauctions.history:
    description: Allows viewing personal auction history.
    default: true
  playerauctions.history.others:
    description: Allows viewing others' auction history.
    default: op
